[build]
  command = "yarn build"
  publish = "website/dist"

[build.environment]
  YARN_FLAGS = "--frozen-lockfile --ignore-scripts"

[functions]
  directory = "functions"

[dev]
  command = "yarn run dev:website"
  autoLaunch = false
  functions = "functions"

[[headers]]
  for = "/*"
  [headers.values]
    access-control-allow-origin: *